name: flutter_colorpicker_example
description: A flutter_colorpicker example Flutter project.
version: 1.0.0+1

publish_to: none

dependencies:
    flutter:
        sdk: flutter
    flutter_colorpicker:
        path: ../
    overlay_tutorial: ^2.0.4

dev_dependencies:
    flutter_lints: ^1.0.0

flutter:
    uses-material-design: true

environment:
    sdk: '>=2.12.0 <3.0.0'
